vich_uploader:
    db_driver: orm
    mappings:
        products:
            uri_prefix: '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_images%'
